apiVersion: v1
kind: Service
metadata:
  name: system-monitor-service
spec:
  selector:
    app: system-monitor
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP